// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/OffchainLabs/prysm/v7/validator/client/iface (interfaces: Validator)
//
// Generated by this command:
//
//	mockgen -package=validator_mock -destination=testing/validator-mock/validator_mock.go github.com/OffchainLabs/prysm/v7/validator/client/iface Validator
//

// Package validator_mock is a generated GoMock package.
package validator_mock

import (
	context "context"
	reflect "reflect"
	time "time"

	event "github.com/OffchainLabs/prysm/v7/api/client/event"
	proposer "github.com/OffchainLabs/prysm/v7/config/proposer"
	primitives "github.com/OffchainLabs/prysm/v7/consensus-types/primitives"
	eth "github.com/OffchainLabs/prysm/v7/proto/prysm/v1alpha1"
	iface "github.com/OffchainLabs/prysm/v7/validator/client/iface"
	keymanager "github.com/OffchainLabs/prysm/v7/validator/keymanager"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// AccountsChangedChan mocks base method.
func (m *MockValidator) AccountsChangedChan() <-chan [][48]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountsChangedChan")
	ret0, _ := ret[0].(<-chan [][48]byte)
	return ret0
}

// AccountsChangedChan indicates an expected call of AccountsChangedChan.
func (mr *MockValidatorMockRecorder) AccountsChangedChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountsChangedChan", reflect.TypeOf((*MockValidator)(nil).AccountsChangedChan))
}

// CheckDoppelGanger mocks base method.
func (m *MockValidator) CheckDoppelGanger(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDoppelGanger", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDoppelGanger indicates an expected call of CheckDoppelGanger.
func (mr *MockValidatorMockRecorder) CheckDoppelGanger(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDoppelGanger", reflect.TypeOf((*MockValidator)(nil).CheckDoppelGanger), ctx)
}

// DeleteGraffiti mocks base method.
func (m *MockValidator) DeleteGraffiti(ctx context.Context, pubKey [48]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGraffiti", ctx, pubKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGraffiti indicates an expected call of DeleteGraffiti.
func (mr *MockValidatorMockRecorder) DeleteGraffiti(ctx, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGraffiti", reflect.TypeOf((*MockValidator)(nil).DeleteGraffiti), ctx, pubKey)
}

// Done mocks base method.
func (m *MockValidator) Done() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Done")
}

// Done indicates an expected call of Done.
func (mr *MockValidatorMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockValidator)(nil).Done))
}

// EnsureEventStream mocks base method.
func (m *MockValidator) EnsureEventStream(ctx context.Context, topics []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnsureEventStream", ctx, topics)
}

// EnsureEventStream indicates an expected call of EnsureEventStream.
func (mr *MockValidatorMockRecorder) EnsureEventStream(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureEventStream", reflect.TypeOf((*MockValidator)(nil).EnsureEventStream), ctx, topics)
}

// EnsureReady mocks base method.
func (m *MockValidator) EnsureReady(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureReady", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnsureReady indicates an expected call of EnsureReady.
func (mr *MockValidatorMockRecorder) EnsureReady(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureReady", reflect.TypeOf((*MockValidator)(nil).EnsureReady), ctx)
}

// EventStreamIsRunning mocks base method.
func (m *MockValidator) EventStreamIsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventStreamIsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// EventStreamIsRunning indicates an expected call of EventStreamIsRunning.
func (mr *MockValidatorMockRecorder) EventStreamIsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventStreamIsRunning", reflect.TypeOf((*MockValidator)(nil).EventStreamIsRunning))
}

// EventsChan mocks base method.
func (m *MockValidator) EventsChan() <-chan *event.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsChan")
	ret0, _ := ret[0].(<-chan *event.Event)
	return ret0
}

// EventsChan indicates an expected call of EventsChan.
func (mr *MockValidatorMockRecorder) EventsChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsChan", reflect.TypeOf((*MockValidator)(nil).EventsChan))
}

// GenesisTime mocks base method.
func (m *MockValidator) GenesisTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenesisTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GenesisTime indicates an expected call of GenesisTime.
func (mr *MockValidatorMockRecorder) GenesisTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenesisTime", reflect.TypeOf((*MockValidator)(nil).GenesisTime))
}

// Graffiti mocks base method.
func (m *MockValidator) Graffiti(ctx context.Context, pubKey [48]byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Graffiti", ctx, pubKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Graffiti indicates an expected call of Graffiti.
func (mr *MockValidatorMockRecorder) Graffiti(ctx, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Graffiti", reflect.TypeOf((*MockValidator)(nil).Graffiti), ctx, pubKey)
}

// HandleKeyReload mocks base method.
func (m *MockValidator) HandleKeyReload(ctx context.Context, currentKeys [][48]byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleKeyReload", ctx, currentKeys)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleKeyReload indicates an expected call of HandleKeyReload.
func (mr *MockValidatorMockRecorder) HandleKeyReload(ctx, currentKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKeyReload", reflect.TypeOf((*MockValidator)(nil).HandleKeyReload), ctx, currentKeys)
}

// Host mocks base method.
func (m *MockValidator) Host() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host")
	ret0, _ := ret[0].(string)
	return ret0
}

// Host indicates an expected call of Host.
func (mr *MockValidatorMockRecorder) Host() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockValidator)(nil).Host))
}

// Keymanager mocks base method.
func (m *MockValidator) Keymanager() (keymanager.IKeymanager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keymanager")
	ret0, _ := ret[0].(keymanager.IKeymanager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keymanager indicates an expected call of Keymanager.
func (mr *MockValidatorMockRecorder) Keymanager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keymanager", reflect.TypeOf((*MockValidator)(nil).Keymanager))
}

// LogSubmissions mocks base method.
func (m *MockValidator) LogSubmissions(slot primitives.Slot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogSubmissions", slot)
}

// LogSubmissions indicates an expected call of LogSubmissions.
func (mr *MockValidatorMockRecorder) LogSubmissions(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSubmissions", reflect.TypeOf((*MockValidator)(nil).LogSubmissions), slot)
}

// LogValidatorGainsAndLosses mocks base method.
func (m *MockValidator) LogValidatorGainsAndLosses(ctx context.Context, slot primitives.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogValidatorGainsAndLosses", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogValidatorGainsAndLosses indicates an expected call of LogValidatorGainsAndLosses.
func (mr *MockValidatorMockRecorder) LogValidatorGainsAndLosses(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogValidatorGainsAndLosses", reflect.TypeOf((*MockValidator)(nil).LogValidatorGainsAndLosses), ctx, slot)
}

// MaybeFetchNextDuties mocks base method.
func (m *MockValidator) MaybeFetchNextDuties(ctx context.Context, slot primitives.Slot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MaybeFetchNextDuties", ctx, slot)
}

// MaybeFetchNextDuties indicates an expected call of MaybeFetchNextDuties.
func (mr *MockValidatorMockRecorder) MaybeFetchNextDuties(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaybeFetchNextDuties", reflect.TypeOf((*MockValidator)(nil).MaybeFetchNextDuties), ctx, slot)
}

// NextSlot mocks base method.
func (m *MockValidator) NextSlot() <-chan primitives.Slot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSlot")
	ret0, _ := ret[0].(<-chan primitives.Slot)
	return ret0
}

// NextSlot indicates an expected call of NextSlot.
func (mr *MockValidatorMockRecorder) NextSlot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSlot", reflect.TypeOf((*MockValidator)(nil).NextSlot))
}

// ProcessEvent mocks base method.
func (m *MockValidator) ProcessEvent(ctx context.Context, arg1 *event.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessEvent", ctx, arg1)
}

// ProcessEvent indicates an expected call of ProcessEvent.
func (mr *MockValidatorMockRecorder) ProcessEvent(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessEvent", reflect.TypeOf((*MockValidator)(nil).ProcessEvent), ctx, arg1)
}

// ProposeBlock mocks base method.
func (m *MockValidator) ProposeBlock(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProposeBlock", ctx, slot, pubKey)
}

// ProposeBlock indicates an expected call of ProposeBlock.
func (mr *MockValidatorMockRecorder) ProposeBlock(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeBlock", reflect.TypeOf((*MockValidator)(nil).ProposeBlock), ctx, slot, pubKey)
}

// ProposerSettings mocks base method.
func (m *MockValidator) ProposerSettings() *proposer.Settings {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposerSettings")
	ret0, _ := ret[0].(*proposer.Settings)
	return ret0
}

// ProposerSettings indicates an expected call of ProposerSettings.
func (mr *MockValidatorMockRecorder) ProposerSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposerSettings", reflect.TypeOf((*MockValidator)(nil).ProposerSettings))
}

// PushProposerSettings mocks base method.
func (m *MockValidator) PushProposerSettings(ctx context.Context, slot primitives.Slot, forceFullPush bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushProposerSettings", ctx, slot, forceFullPush)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushProposerSettings indicates an expected call of PushProposerSettings.
func (mr *MockValidatorMockRecorder) PushProposerSettings(ctx, slot, forceFullPush any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushProposerSettings", reflect.TypeOf((*MockValidator)(nil).PushProposerSettings), ctx, slot, forceFullPush)
}

// RolesAt mocks base method.
func (m *MockValidator) RolesAt(ctx context.Context, slot primitives.Slot) (map[[48]byte][]iface.ValidatorRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RolesAt", ctx, slot)
	ret0, _ := ret[0].(map[[48]byte][]iface.ValidatorRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RolesAt indicates an expected call of RolesAt.
func (mr *MockValidatorMockRecorder) RolesAt(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RolesAt", reflect.TypeOf((*MockValidator)(nil).RolesAt), ctx, slot)
}

// SetGraffiti mocks base method.
func (m *MockValidator) SetGraffiti(ctx context.Context, pubKey [48]byte, graffiti []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGraffiti", ctx, pubKey, graffiti)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGraffiti indicates an expected call of SetGraffiti.
func (mr *MockValidatorMockRecorder) SetGraffiti(ctx, pubKey, graffiti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGraffiti", reflect.TypeOf((*MockValidator)(nil).SetGraffiti), ctx, pubKey, graffiti)
}

// SetProposerSettings mocks base method.
func (m *MockValidator) SetProposerSettings(arg0 context.Context, arg1 *proposer.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProposerSettings", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProposerSettings indicates an expected call of SetProposerSettings.
func (mr *MockValidatorMockRecorder) SetProposerSettings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProposerSettings", reflect.TypeOf((*MockValidator)(nil).SetProposerSettings), arg0, arg1)
}

// SetTicker mocks base method.
func (m *MockValidator) SetTicker() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTicker")
}

// SetTicker indicates an expected call of SetTicker.
func (mr *MockValidatorMockRecorder) SetTicker() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTicker", reflect.TypeOf((*MockValidator)(nil).SetTicker))
}

// SignValidatorRegistrationRequest mocks base method.
func (m *MockValidator) SignValidatorRegistrationRequest(ctx context.Context, signer iface.SigningFunc, newValidatorRegistration *eth.ValidatorRegistrationV1) (*eth.SignedValidatorRegistrationV1, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignValidatorRegistrationRequest", ctx, signer, newValidatorRegistration)
	ret0, _ := ret[0].(*eth.SignedValidatorRegistrationV1)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignValidatorRegistrationRequest indicates an expected call of SignValidatorRegistrationRequest.
func (mr *MockValidatorMockRecorder) SignValidatorRegistrationRequest(ctx, signer, newValidatorRegistration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignValidatorRegistrationRequest", reflect.TypeOf((*MockValidator)(nil).SignValidatorRegistrationRequest), ctx, signer, newValidatorRegistration)
}

// SlotDeadline mocks base method.
func (m *MockValidator) SlotDeadline(slot primitives.Slot) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SlotDeadline", slot)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// SlotDeadline indicates an expected call of SlotDeadline.
func (mr *MockValidatorMockRecorder) SlotDeadline(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlotDeadline", reflect.TypeOf((*MockValidator)(nil).SlotDeadline), slot)
}

// SubmitAggregateAndProof mocks base method.
func (m *MockValidator) SubmitAggregateAndProof(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubmitAggregateAndProof", ctx, slot, pubKey)
}

// SubmitAggregateAndProof indicates an expected call of SubmitAggregateAndProof.
func (mr *MockValidatorMockRecorder) SubmitAggregateAndProof(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAggregateAndProof", reflect.TypeOf((*MockValidator)(nil).SubmitAggregateAndProof), ctx, slot, pubKey)
}

// SubmitAttestation mocks base method.
func (m *MockValidator) SubmitAttestation(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubmitAttestation", ctx, slot, pubKey)
}

// SubmitAttestation indicates an expected call of SubmitAttestation.
func (mr *MockValidatorMockRecorder) SubmitAttestation(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAttestation", reflect.TypeOf((*MockValidator)(nil).SubmitAttestation), ctx, slot, pubKey)
}

// SubmitPayloadAttestation mocks base method.
func (m *MockValidator) SubmitPayloadAttestation(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubmitPayloadAttestation", ctx, slot, pubKey)
}

// SubmitPayloadAttestation indicates an expected call of SubmitPayloadAttestation.
func (mr *MockValidatorMockRecorder) SubmitPayloadAttestation(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPayloadAttestation", reflect.TypeOf((*MockValidator)(nil).SubmitPayloadAttestation), ctx, slot, pubKey)
}

// SubmitSignedContributionAndProof mocks base method.
func (m *MockValidator) SubmitSignedContributionAndProof(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubmitSignedContributionAndProof", ctx, slot, pubKey)
}

// SubmitSignedContributionAndProof indicates an expected call of SubmitSignedContributionAndProof.
func (mr *MockValidatorMockRecorder) SubmitSignedContributionAndProof(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSignedContributionAndProof", reflect.TypeOf((*MockValidator)(nil).SubmitSignedContributionAndProof), ctx, slot, pubKey)
}

// SubmitSyncCommitteeMessage mocks base method.
func (m *MockValidator) SubmitSyncCommitteeMessage(ctx context.Context, slot primitives.Slot, pubKey [48]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubmitSyncCommitteeMessage", ctx, slot, pubKey)
}

// SubmitSyncCommitteeMessage indicates an expected call of SubmitSyncCommitteeMessage.
func (mr *MockValidatorMockRecorder) SubmitSyncCommitteeMessage(ctx, slot, pubKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitSyncCommitteeMessage", reflect.TypeOf((*MockValidator)(nil).SubmitSyncCommitteeMessage), ctx, slot, pubKey)
}

// UpdateDomainDataCaches mocks base method.
func (m *MockValidator) UpdateDomainDataCaches(ctx context.Context, slot primitives.Slot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateDomainDataCaches", ctx, slot)
}

// UpdateDomainDataCaches indicates an expected call of UpdateDomainDataCaches.
func (mr *MockValidatorMockRecorder) UpdateDomainDataCaches(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDomainDataCaches", reflect.TypeOf((*MockValidator)(nil).UpdateDomainDataCaches), ctx, slot)
}

// UpdateDuties mocks base method.
func (m *MockValidator) UpdateDuties(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDuties", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDuties indicates an expected call of UpdateDuties.
func (mr *MockValidatorMockRecorder) UpdateDuties(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDuties", reflect.TypeOf((*MockValidator)(nil).UpdateDuties), ctx)
}

// WaitForActivation mocks base method.
func (m *MockValidator) WaitForActivation(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForActivation", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForActivation indicates an expected call of WaitForActivation.
func (mr *MockValidatorMockRecorder) WaitForActivation(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForActivation", reflect.TypeOf((*MockValidator)(nil).WaitForActivation), ctx)
}

// WaitForChainStart mocks base method.
func (m *MockValidator) WaitForChainStart(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForChainStart", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForChainStart indicates an expected call of WaitForChainStart.
func (mr *MockValidatorMockRecorder) WaitForChainStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForChainStart", reflect.TypeOf((*MockValidator)(nil).WaitForChainStart), ctx)
}

// WaitForKeymanagerInitialization mocks base method.
func (m *MockValidator) WaitForKeymanagerInitialization(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForKeymanagerInitialization", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForKeymanagerInitialization indicates an expected call of WaitForKeymanagerInitialization.
func (mr *MockValidatorMockRecorder) WaitForKeymanagerInitialization(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForKeymanagerInitialization", reflect.TypeOf((*MockValidator)(nil).WaitForKeymanagerInitialization), ctx)
}

// WaitForSync mocks base method.
func (m *MockValidator) WaitForSync(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForSync", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForSync indicates an expected call of WaitForSync.
func (mr *MockValidatorMockRecorder) WaitForSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForSync", reflect.TypeOf((*MockValidator)(nil).WaitForSync), ctx)
}
